service: bet365-stats

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-2

functions:
  hello:
    handler: src/app.handler
    events:
      - schedule: cron(0/6 14-23 * * ? *)
      - schedule: cron(0/6 0-3 * * ? *)
